spring:
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver